import react from '@astrojs/react'
import sitemap from '@astrojs/sitemap'
import { defaultLocale, locales } from '@mochifile/i18n'
import tailwindcss from '@tailwindcss/vite'
import { defineConfig, fontProviders } from 'astro/config'
import designTokens from '../../docs/design-system/tokens.json' with { type: 'json' }
import { FONTS, fontUrl, weightRange } from './fonts/fonts.ts'
import cspHashes from './integrations/csp-hashes.ts'
import searchIndexing from './integrations/search-indexing.ts'
import sitemapAlternates from './integrations/sitemap-alternates.ts'
import thirdPartyLicenses from './integrations/third-party-licenses.ts'
import { ALLOW_SEARCH_INDEXING } from './search-indexing.ts'

export const SITE_URL = 'https://mochifile.com'

/** Include the `_template` tool in a production build (used by e2e tests only). */
const includeTemplateTool = process.env.MOCHIFILE_INCLUDE_TEMPLATE === 'true'

const alternates = sitemapAlternates()

/** `Fredoka, "Noto Sans", system-ui, sans-serif` → `["Noto Sans", "system-ui", "sans-serif"]`. */
const fallbacksOf = (family: string) =>
  family
    .split(',')
    .slice(1)
    .map((name) => name.trim().replace(/^"(.*)"$/, '$1'))

export default defineConfig({
  site: SITE_URL,
  // Brand fonts, self-hosted (the CSP allows only 'self'; builds stay offline): subsets of the
  // Fontsource files for the characters en and pt need and the weights in use, generated by
  // fonts/subset.ts (ADR 0021). Fallbacks come from tokens.json; Astro adds metric-matched
  // fallback faces so text does not shift when the fonts arrive. Noto Sans stays in the stack,
  // not downloaded.
  fonts: [
    {
      provider: fontProviders.local(),
      name: FONTS.fredoka.family,
      cssVariable: '--font-fredoka',
      fallbacks: fallbacksOf(designTokens.type.families[FONTS.fredoka.role]),
      options: {
        variants: [
          { src: [fontUrl(FONTS.fredoka)], weight: weightRange(FONTS.fredoka), style: 'normal' },
        ],
      },
    },
    {
      provider: fontProviders.local(),
      name: FONTS.figtree.family,
      cssVariable: '--font-figtree',
      display: 'optional',
      fallbacks: fallbacksOf(designTokens.type.families[FONTS.figtree.role]),
      options: {
        variants: [
          { src: [fontUrl(FONTS.figtree)], weight: weightRange(FONTS.figtree), style: 'normal' },
        ],
      },
    },
  ],
  output: 'static',
  trailingSlash: 'always',
  build: {
    format: 'directory',
    // External stylesheets only, so the CSP needs no 'unsafe-inline' for styles.
    inlineStylesheets: 'never',
  },
  i18n: {
    locales: [...locales],
    defaultLocale,
    routing: {
      // English lives at the root; other locales under /<locale>/.
      prefixDefaultLocale: false,
      // Never redirect based on the visitor's language (ADR 0007).
      redirectToDefaultLocale: false,
    },
  },
  integrations: [
    react(),
    alternates.integration,
    // hreflang alternates come from each built page, not from sitemap's i18n option, which
    // assumes the same path in every locale (wrong for translated tool slugs).
    sitemap({ serialize: alternates.serialize }),
    // Pre-launch noindex switch: see search-indexing.ts and ADR 0014.
    searchIndexing({ allowIndexing: ALLOW_SEARCH_INDEXING }),
    // /third-party-licenses.txt: notices of the code shipped to browsers (ADR 0016).
    thirdPartyLicenses(),
    // Must run after every other integration has written its HTML.
    cspHashes(),
  ],
  vite: {
    plugins: [tailwindcss()],
    worker: { format: 'es' },
    // jSquash loads its .wasm files relative to its own modules; pre-bundling breaks that in dev.
    optimizeDeps: {
      exclude: [
        '@jsquash/jpeg',
        '@jsquash/webp',
        '@jsquash/png',
        '@jsquash/oxipng',
        '@jsquash/resize',
      ],
    },
    define: {
      // Statically replaced, so production builds drop the template tool's code entirely.
      'import.meta.env.MOCHIFILE_INCLUDE_TEMPLATE': JSON.stringify(includeTemplateTool),
    },
  },
})
