/**
 * The brand fonts as shipped: subsets of the Fontsource variable files, limited to the
 * characters English and Portuguese need and to the weights the design system uses (ADR 0021).
 * The woff2 files next to this module are generated by subset.ts and committed.
 */
import { dirname } from 'node:path'

const range = (from: number, to: number) =>
  Array.from({ length: to - from + 1 }, (_, index) => String.fromCodePoint(from + index)).join('')

/**
 * Every character the fonts draw. Printable ASCII and Latin-1 (all Portuguese letters, ×, ·,
 * no-break space), the wordmark's dotless ı, typographic punctuation, → and −, and the spaces
 * number formatting may produce. Characters outside it fall back to the next font in the
 * stack; a unit test checks that the site's text stays inside it.
 */
export const CHARSET = [
  range(0x20, 0x7e),
  range(0xa0, 0xff),
  'ı', // ı
  ' ‑ ', // thin space, non-breaking hyphen, narrow no-break space
  '–—', // – —
  '‘’“”', // ‘ ’ “ ”
  '•…›', // • … ›
  '→−', // → −
].join('')

export interface SubsetFont {
  /** Family name. */
  family: string
  /** Its family in tokens.json, whose fallback stack it uses. */
  role: 'display' | 'sans'
  /** Fontsource package and Latin variable file the subset is made from. */
  source: { pkg: string; file: string }
  /** Weight range kept (design system README › Typography). */
  weight: { min: number; max: number }
  /** Output file, next to this module. */
  output: string
}

export const FONTS = {
  fredoka: {
    family: 'Fredoka',
    role: 'display',
    source: { pkg: '@fontsource-variable/fredoka', file: 'fredoka-latin-wght-normal.woff2' },
    weight: { min: 500, max: 700 },
    output: 'fredoka-subset.woff2',
  },
  figtree: {
    family: 'Figtree',
    role: 'sans',
    source: { pkg: '@fontsource-variable/figtree', file: 'figtree-latin-wght-normal.woff2' },
    weight: { min: 400, max: 700 },
    output: 'figtree-subset.woff2',
  },
} as const satisfies Record<string, SubsetFont>

/** Weight range in the form `@font-face` expects, e.g. `500 700`. */
export const weightRange = (font: SubsetFont) => `${font.weight.min} ${font.weight.max}`

/** URL of a committed subset file. */
export const fontUrl = (font: SubsetFont) => new URL(font.output, import.meta.url)

/** Folder of the committed subset files. */
export const FONTS_DIR = dirname(new URL(import.meta.url).pathname)
